name: procs
version: &version v0.14.10
summary: A modern replacement for ps written in Rust
description: |
  procs is a tool to display process information.
base: core18
license: MIT

confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf

apps:
  procs:
    command: procs

parts:
  procs:
    source: https://github.com/dalance/procs.git
    source-tag: *version
    plugin: rust
    stage-packages:
      - libc6
      - libgcc1
      - libstdc++6
      - zlib1g
